os_self="${os_self:-linux}"
arch_self="${arch_self:-x86_64}"
version_zig="${version_zig:-0.17.0}"
pre_release="${pre_release:-dev.2375}"
build_metadata="${build_metadata:-d8aab4878}"
format="${format:-tar.xz}"
full_version="${version_zig}-${pre_release}+${build_metadata}"
full_name="zig-${arch_self}-${os_self}-${full_version}"
name_archive="zig-${arch_self}-${os_self}-${version_zig}-${pre_release}+${build_metadata}.${format}"
addr_zig="https://ziglang.org/builds/${name_archive}"
name_folder="zig-${arch_self}-${os_self}-${version_zig}-${pre-release}"

home_zig="${HOME}/zig"
path_zigfile="${home_zig}/${name_folder}"
zigfile="${path_zigfile}/zig"


os_build_target="${os_build_target:-linux}"
arch_build_target="${arch_build_target:-x86_64}"
libc_build_target="${libc_build_target:-musl}"
build_target="${build_target:-${arch_build_target}-${os_build_target}-${libc_build_target}}"
traget_output="$(pwd)/build/${os_build_target}/${arch_build_target}"
addr_repository="https://github.com/madler/zlib.git"
path_zlib="$(pwd)/zlib"
headers_output="${traget_output}/headers"
